### ISSUE TITLE
accent color exception - is accent color required?

### ISSUE THREAD

**Issue by josh-m-sharpe** [arnesson/cordova-plugin-firebase#270]
```
Exception android.content.res.Resources$NotFoundException: Resource ID #0x0
android.content.res.Resources.getValue (Resources.java:2558)
android.content.res.Resources.getColor (Resources.java:2170)
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:105)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzo ()
com.google.firebase.messaging.FirebaseMessagingService.zzn ()
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

Which is here? https://github.com/arnesson/cordova-plugin-firebase/blob/master/src/android/FirebasePluginMessagingService.java#L105

The [readme](https://github.com/arnesson/cordova-plugin-firebase#notification-colors) suggests that I 'can' set the accent color, but that doesn't imply that it is required to do so -- is there a bug here?  Is accent color required?

**Comment by GerardSoleCa** [comment]
Same problem here. Will start debugging!

**Comment by hakimdja** [comment]
Hello,
Correct the bug please, replace .LOLLIPOP BY .M in FirebasePluginMessagingService.java
because the function call require api level 23.

old:
if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP)
{
int accentID = getResources().getIdentifier("accent", "color", getPackageName());
notificationBuilder.setColor(getResources().getColor(accentID, null));				
 }

new:
if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.M)
{
int accentID = getResources().getIdentifier("accent", "color", getPackageName());
notificationBuilder.setColor(getResources().getColor(accentID, null));				
}

**Comment by josh-m-sharpe** [comment]
@hakimdja if you think you help the maintainers out and submit a PR?

**Comment by hakimdja** [comment]
@josh-m-sharpe I leave it to you to do it, if you want

**Comment by kotmatpockuh** [comment]
Same crash:
`
Exception android.content.res.Resources$NotFoundException: Resource ID #0x0
android.content.res.Resources.getValue (Resources.java:1369)
android.content.res.MiuiResources.getValue (MiuiResources.java:145)
android.content.res.Resources.getColor (Resources.java:981)
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:105)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzo ()
com.google.firebase.messaging.FirebaseMessagingService.zzn ()
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
`

**Comment by josh-m-sharpe** [comment]
@hakimdja  I'm not sure about this fix.  I extensively tested push notifications on a 5.1 device and didn't see this problem.  So, i'm not sure what good pushing this to lollipop will do.

Could you at least provide a reference for "because the function call require api level 23."  Which function call are you referring to?

**Comment by hakimdja** [comment]
@josh-m-sharpe 
in line : notificationBuilder.setColor(getResources().getColor(accentID, null));

getColor added in API level 23 :
https://developer.android.com/reference/android/content/res/Resources.html#getColor(int,%20android.content.res.Resources.Theme)

**Comment by hakimdja** [comment]
Sorry, I just saw that it was corrected :
https://github.com/arnesson/cordova-plugin-firebase/pull/226

**Comment by josh-m-sharpe** [comment]
doesn't exactly look like a fix... the comments over there suggest it's still broken.

**Comment by josh-m-sharpe** [comment]
subsequently fixed here: https://github.com/arnesson/cordova-plugin-firebase/commit/4eaeca90c11cda60f07299ff4bcab32140f41c2a

**Comment by larssn** [comment]
We're also seeing the problem. Same crash.

We can reproduce the problem by sending a notification to the android device while the app is in the foreground (notification is received just fine), then opening the app, and sending another message:
crashes every time.

**Comment by viananicolas** [comment]
Removing the second argument from getColor(); fixed the issue for me.

if(android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.LOLLIPOP)
{
int accentID = getResources().getIdentifier("accent", "color", getPackageName());
notificationBuilder.setColor(getResources().getColor(accentID));
}

**Comment by morariu** [comment]
Hi. Has this been fixed? I am getting same crash when receiving push notifications. Tried the fixes above but nothing worked. 

Here is the crash report:

```
Exception android.content.res.Resources$NotFoundException: Resource ID #0x0
android.content.res.Resources.getValue (Resources.java:1551)
android.content.res.Resources.getColor (Resources.java:1102)
org.apache.cordova.firebase.FirebasePluginMessagingService.sendNotification (FirebasePluginMessagingService.java:105)
org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived (FirebasePluginMessagingService.java:71)
com.google.firebase.messaging.FirebaseMessagingService.zzo ()
com.google.firebase.messaging.FirebaseMessagingService.zzn ()
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)
```

**Comment by morariu** [comment]
It seems it's sending an empty push notification. App crashes in Android 6 on receiving the empty push while in Android 5.0.2 is receiving a second blank push (in addition to the correct push expected). 

I've commented line 71 in FirebasePluginMessagingService.java and got rid of the issue but of course that should be taken care of in a more elegant manner.

**Comment by canado** [comment]
I have the same bug
Can you confirm I have to use 
 notificationBuilder.setColor(getResources().getColor(accentID));  with  no null as second param

OR maybe something like this

notificationBuilder.setColor(ContextCompat.getColor(accentID, R.color.color_name));

but I don't know what to use for R.color.color_name

Please help : )

**Comment by soumak77** [comment]
Can anyone confirm whether this is still an issue with the latest version?

**Comment by soumak77** [comment]
Closing due to inactivity.  Please reopen if there is something we need to fix.
