### ISSUE TITLE
Returning token as null

### ISSUE THREAD

**Issue by akaushik79** [arnesson/cordova-plugin-firebase#412]
Hi,

Thanks for the great work you have been doing so far. I am using this plugin in my Ionic app and it was working fine till yesterday. I upgraded the plugin to 0.1.24 post which i started facing the issue #410 but this issue is gone now. I am facing a new issue where token is being returned as "Null".  I am able to subscribe to the topics but when i send a notifications to that topic then my device is not able to receive that.

I also noticed the google-services.json file copied by this plugin in platform/android folder was empty but token value is still null even after updating google-services.json. Would request you to have a look.

Happy to share my code snippets in case required.

Cheers
Ankit

**Comment by ben-8409** [comment]
This issue should be fixed in the current master. Please try with the master version from git until there is a new release.

**Comment by akaushik79** [comment]
Thank you. Just updated my plugin and it has started providing the token. Somehow my device is still not able to receive push notifications. Do i need to make some other changes?
