### ISSUE TITLE
FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

### ISSUE THREAD

**Issue by jdileep14** [arnesson/cordova-plugin-firebase#518]
Hi i am using firebase plugin .I am able to receive push notifications using  android but in iOS i am getting this message 

FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

**Comment by Yuripetusko** [comment]
Same here, when take app from foreground to background i receive this message in xcode debugger

**Comment by alaborderie** [comment]
Having the exact same issue!
```
[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented
```

**Comment by Yuripetusko** [comment]
ok I found a solution by installing this fork directly `cordova plugin add https://github.com/transistorsoft/cordova-plugin-firebase.git --variable GOOGLE_API_VERSION=11.6.0` and then there's small thing that needs to be done in build.gradle once platform is added 

```
defaultConfig {
  multiDexEnabled true
}
```

https://stackoverflow.com/questions/33717886/errorexecution-failed-for-task-apptransformclasseswithdexfordebug

**Comment by alaborderie** [comment]
I don't get how it could solve anything as `master` is event with @robertarnesson  `master` but whatever ahah! Going to try thanks for the tip @Yuripetusko

**Comment by alaborderie** [comment]
Not working on iPhone 7 iOS 11.2.1 :/

**Comment by write2sv** [comment]
Not sure if this is the case for you guys.
I have faced the same issue and it was because I did not do IOS App configuration under my apps firebase console. By the way I am using key based instead of certificates as it is now recommended by firebase.

**Comment by xrnm** [comment]
A few notes. You may need to call `window.FirebasePlugin.grantPermission();` on iOS. I also don't believe push notifications can be tested in iOS simulator.

**Comment by alaborderie** [comment]
I have my iOS App conf in firebase.
It used to work perfectly on older versions of iOS.
I use `grantPermission()` and it works just fine! I even tried an old version of my app (Where notifications where working) and I could not receive the notification either... Do not know what to do now!

**Comment by alaborderie** [comment]
Okay I found a solution for me!

I had to create a new app in firebase console, as my `Bundle id` had a typo for iOS. I don't know how it worked before iOS 11 but whatever.

I had to create new certificates upload them and use the new `GoogleService-Info.plist`...

I now have notifications for both iOS and Android working as expected !

Sorry for the bothering and good luck finding your mistakes !

**Comment by michaelreiser** [comment]
@alaborderie  Are you using the latest 0.1.25 release?  I'm having the same issue here.  So far, nothing is working.  I can get the token just fine, but get same error as everyone else.

I also tried setting FirebaseAppDelegateProxyEnabled in the app-info.plist as mentioned in other forums.  No luck

**Comment by xrnm** [comment]
Solved on our end by adding `grantPermission()` and turning the push notification capability on inside xcode. For some reason it got turned off in the move to 9.2

**Comment by alaborderie** [comment]
@michaelreiser I'm using 0.1.25!
As @xrnm mentioned I had to turn Push Notification back ON in Capability in XCode

**Comment by xrnm** [comment]
Looks like this isn't an issue with the plugin. This can probably be closed.

**Comment by michaelreiser** [comment]
I can confirm.  I had to turn on Notifications in XCode.  I also had to remove the iOS cordova platform and re-add it before notifications finally started working.

**Comment by manojkumardesai** [comment]
I got it resolved by implementing didReceiveMessage method in delegate file. It started working after that. Has the plugin missed this method? - For iOS version above 10

**Comment by fjckls** [comment]
I'm still having the similar issues - no push notifications. If APP is in foregraound I get `FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented`. @manojkumardesai how did you implement that method?

**Comment by asolagmbh** [comment]
Same problem here...
@manojkumardesai how have you fixed the problem?

**Comment by espvar** [comment]
Same problem here!

**Comment by manojkumardesai** [comment]
I used the below code in AppDelegate.m 
Hope this helps...

```
window.FirebasePlugin.grantPermission();
window.FirebasePlugin.onTokenRefresh(function(token) {
    console.log(token);
}, function(error) {
  console.error(error);
});
window.FirebasePlugin.hasPermission(function(data){
  console.log(data.isEnabled);
});
```

you can find more from this link:
https://github.com/arnesson/cordova-plugin-firebase/issues/252

and full AppDelegate.m file here

https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m#L60-L83

**Comment by espvar** [comment]
I am sorry @manojkumardesai but i cannot find a similar file as your https://github.com/firebase/quickstart-ios/blob/master/messaging/MessagingExample/AppDelegate.m#L60-L83
Where is it located? My AppDelegate+FirebasePluginFile.m file does not look like that at all. I'am using cordova-plugin-firebase 0.1.25

**Comment by manojkumardesai** [comment]
its the same file... here is the full code of my file.

```
#import "AppDelegate+FirebasePlugin.h"

#import "FirebasePlugin.h"

#import "Firebase.h"

#import <objc/runtime.h>



#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

@import UserNotifications;

#endif



// Implement UNUserNotificationCenterDelegate to receive display notification via APNS for devices

// running iOS 10 and above. Implement FIRMessagingDelegate to receive data message via FCM for

// devices running iOS 10 and above.

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

@interface AppDelegate () <UNUserNotificationCenterDelegate, FIRMessagingDelegate>

@end

#endif



#define kApplicationInBackgroundKey @"applicationInBackground"



@implementation AppDelegate (FirebasePlugin)



+ (void)load {

    Method original = class_getInstanceMethod(self, @selector(application:didFinishLaunchingWithOptions:));

    Method swizzled = class_getInstanceMethod(self, @selector(application:swizzledDidFinishLaunchingWithOptions:));

    method_exchangeImplementations(original, swizzled);

}



- (void)setApplicationInBackground:(NSNumber *)applicationInBackground {

    objc_setAssociatedObject(self, kApplicationInBackgroundKey, applicationInBackground, OBJC_ASSOCIATION_RETAIN_NONATOMIC);

}



- (NSNumber *)applicationInBackground {

    return objc_getAssociatedObject(self, kApplicationInBackgroundKey);

}



- (BOOL)application:(UIApplication *)application swizzledDidFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

    [self application:application swizzledDidFinishLaunchingWithOptions:launchOptions];

    

    if(![FIRApp defaultApp]) {

        [FIRApp configure];

    }

    

    // [START set_messaging_delegate]

    [FIRMessaging messaging].delegate = self;

    // [END set_messaging_delegate]

    

    // Register for remote notifications. This shows a permission dialog on first run, to

    // show the dialog at a more appropriate time move this registration accordingly.

    if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_7_1) {

        // iOS 7.1 or earlier. Disable the deprecation warnings.

#pragma clang diagnostic push

#pragma clang diagnostic ignored "-Wdeprecated-declarations"

        UIRemoteNotificationType allNotificationTypes =

        (UIRemoteNotificationTypeSound |

         UIRemoteNotificationTypeAlert |

         UIRemoteNotificationTypeBadge);

        [application registerForRemoteNotificationTypes:allNotificationTypes];

#pragma clang diagnostic pop

    } else {

        // iOS 8 or later

        // [START register_for_notifications]

        if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_9_x_Max) {

            UIUserNotificationType allNotificationTypes =

            (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);

            UIUserNotificationSettings *settings =

            [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];

            [application registerUserNotificationSettings:settings];

        } else {

            // iOS 10 or later

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

            // For iOS 10 display notification (sent via APNS)

            [UNUserNotificationCenter currentNotificationCenter].delegate = self;

            UNAuthorizationOptions authOptions =

            UNAuthorizationOptionAlert

            | UNAuthorizationOptionSound

            | UNAuthorizationOptionBadge;

            [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {

            }];

#endif

        }[application registerForRemoteNotifications];

        // [END register_for_notifications]

    }

    // Pasting before this

    

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)

                                                 name:kFIRInstanceIDTokenRefreshNotification object:nil];

    

    self.applicationInBackground = @(YES);

    

    return YES;

}



- (void)applicationDidBecomeActive:(UIApplication *)application {

    [self connectToFcm];

    self.applicationInBackground = @(NO);

}



- (void)applicationDidEnterBackground:(UIApplication *)application {

    [[FIRMessaging messaging] disconnect];

    self.applicationInBackground = @(YES);

    NSLog(@"Disconnected from FCM");

}



- (void)tokenRefreshNotification:(NSNotification *)notification {

    // Note that this callback will be fired everytime a new token is generated, including the first

    // time. So if you need to retrieve the token as soon as it is available this is where that

    // should be done.

    NSString *refreshedToken = [[FIRInstanceID instanceID] token];

    NSLog(@"InstanceID token: %@", refreshedToken);

    

    // Connect to FCM since connection may have failed when attempted before having a token.

    [self connectToFcm];



    [FirebasePlugin.firebasePlugin sendToken:refreshedToken];

}



- (void)connectToFcm {

    [[FIRMessaging messaging] connectWithCompletion:^(NSError * _Nullable error) {

        if (error != nil) {

            NSLog(@"Unable to connect to FCM. %@", error);

        } else {

            NSLog(@"Connected to FCM.");

            NSString *refreshedToken = [[FIRInstanceID instanceID] token];

            NSLog(@"InstanceID token: %@", refreshedToken);

        }

    }];

}



- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {

    NSDictionary *mutableUserInfo = [userInfo mutableCopy];

    

    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];

    

    // Pring full message.

    NSLog(@"%@", mutableUserInfo);

    

    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];

}



- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo

    fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {



    NSDictionary *mutableUserInfo = [userInfo mutableCopy];

    

    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];

    

    // Pring full message.

    NSLog(@"%@", mutableUserInfo);

    

    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];

}

    

    // [START ios_10_data_message]

    // Receive data messages on iOS 10+ directly from FCM (bypassing APNs) when the app is in the foreground.

    // To enable direct data messages, you can set [Messaging messaging].shouldEstablishDirectChannel to YES.

- (void)messaging:(FIRMessaging *)messaging didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {

    NSLog(@"Received data message: %@", remoteMessage.appData);

}

    // [END ios_10_data_message]

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

- (void)userNotificationCenter:(UNUserNotificationCenter *)center

       willPresentNotification:(UNNotification *)notification

         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {

    NSDictionary *mutableUserInfo = [notification.request.content.userInfo mutableCopy];

    

    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];

    

    // Pring full message.

    NSLog(@"%@", mutableUserInfo);

    

    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];

}



// Receive data message on iOS 10 devices.

- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {

    // Print full message

    NSLog(@"%@", [remoteMessage appData]);

}

#endif



@end
```

**Comment by enolcasielles** [comment]
I have used @manojkumardesai  code in AppDelegate+FirebasePlugin.m but I continue getting `FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented` message. I don´t understand the reason because this method is implemented... @espvar Have you fixed your problem?

**Comment by espvar** [comment]
@enolcasielles, His code fixed it for me! 
I repllaced the code in AppDelegate+FirebasePlugin.m in the Firebase plugin in my cordova project and did a new build to xcode.

**Comment by besigo** [comment]
We have been encountering the problem intermittently after you unregister() on log out and log back in, after updates to iOS or updates to the app.  And the solution has been to uninstall and reinstall the app.

**Comment by enolcasielles** [comment]
Finally I solved my problem, besides using @manojkumardesai code, removing `FirebaseAppDelegateProxyEnabled` of Info.plist. Thanks!

**Comment by chliangGoogle** [comment]
You need to implement the following callback function in your AppDelegate.m. 
- (void)messaging:(nonnull FIRMessaging *)messaging
    didReceiveMessage:(nonnull FIRMessagingRemoteMessage *)remoteMessage

And don't forget to assign delegate as well:
  [FIRMessaging messaging].delegate = self;

**Comment by nekator** [comment]
To solve the Problem i added the following code to my config.xml

`        <edit-config file="*-Info.plist" mode="merge" target="FirebaseAppDelegateProxyEnabled">
            <true />
        </edit-config>
`
Based on this information from FIRMessaging.h file:
`/**
 *  Use this to track message delivery and analytics for messages, typically
 *  when you receive a notification in `application:didReceiveRemoteNotification:`.
 *  However, you only need to call this if you set the `FirebaseAppDelegateProxyEnabled`
 *  flag to `NO` in your Info.plist. If `FirebaseAppDelegateProxyEnabled` is either missing
 *  or set to `YES` in your Info.plist, the library will call this automatically.
 *
 *  @param message The downstream message received by the application.
 *
 *  @return Information about the downstream message.
 */
- (nonnull FIRMessagingMessageInfo *)appDidReceiveMessage:(nonnull NSDictionary *)message;`

**Comment by rikbauwens** [comment]
@besigo We have been encountering the same issue on app updates of the app. I removed the unregister() function and replaced it with one which just removes the Push Token from the User Profile. Still the same issue. Did you manage to solve this?

**Comment by t2wu** [comment]
Tried manojkumardesai code. It appears to work.

If it is an delegate method that's not implemented, the responsibility definitely fall on the part of the plugin.

That said though, I haven't updated the plugin for a while. It's hard for me to do so though, currently it is difficult for me to even add/remove plugin for some unknown reason. I got to remake the project.

**Comment by soumak77** [comment]
closing as resolved

**Comment by soulemanou** [comment]
hello guys sorry to disturb but i a have being having these error **[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented .** i have tried all the solutions you guys have suggested above but none of them worked for me .please please  .help me ,someone help please. These has really being a nightmare for me

**Comment by soulemanou** [comment]
hello guys sorry to disturb but i  have being having these error **[Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented .** i have tried all the solutions you guys have suggested above but none of them worked for me .please please .help me ,someone help please. These has really being a nightmare for me

**Comment by chliangGoogle** [comment]
@soulemanou  
Are you using direct channel to receive data message?Have you tried implementing FIRMessagingDelegate's-messaging:didReceiveMessage: in your app delegate?

**Comment by soulemanou** [comment]
@chliangGoogle thank you for your answer. i am using an ionic plugin called cordova-plugin-firabase .My FIRMessagingDelegate's-messaging:didReceiveMessage: is clearly being implemented in  My AppDelegate+FirebasePluginFile.m file but for some reason the method is not called .i don't know why.

**Comment by soulemanou** [comment]
this my AppDelegate+FirebaseFile.m file


#import "AppDelegate+FirebasePlugin.h"

#import "FirebasePlugin.h"

#import "Firebase.h"

#import <objc/runtime.h>

@import  FirebaseMessaging;
@import  UserNotifications;

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

@import UserNotifications;

#endif



// Implement UNUserNotificationCenterDelegate to receive display notification via APNS for devices

// running iOS 10 and above. Implement FIRMessagingDelegate to receive data message via FCM for

// devices running iOS 10 and above.

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

@interface AppDelegate () <UNUserNotificationCenterDelegate, FIRMessagingDelegate>

@end

#endif



#define kApplicationInBackgroundKey @"applicationInBackground"



@implementation AppDelegate (FirebasePlugin)



+ (void)load {
    
    Method original = class_getInstanceMethod(self, @selector(application:didFinishLaunchingWithOptions:));
    
    Method swizzled = class_getInstanceMethod(self, @selector(application:swizzledDidFinishLaunchingWithOptions:));
    
    method_exchangeImplementations(original, swizzled);
    
}



- (void)setApplicationInBackground:(NSNumber *)applicationInBackground {
    
    objc_setAssociatedObject(self, kApplicationInBackgroundKey, applicationInBackground, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    
}



- (NSNumber *)applicationInBackground {
    
    return objc_getAssociatedObject(self, kApplicationInBackgroundKey);
    
}



- (BOOL)application:(UIApplication *)application swizzledDidFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    
    [self application:application swizzledDidFinishLaunchingWithOptions:launchOptions];
    
    
    
    if(![FIRApp defaultApp]) {
        
        [FIRApp configure];
        
    }
    
   // [FIRApp configure];
    
    // [START set_messaging_delegate]
    
    [FIRMessaging messaging].delegate = self;
    
    // [END set_messaging_delegate]
  // [FIRMessaging messaging].shouldEstablishDirectChannel =  true;
    
    
    // Register for remote notifications. This shows a permission dialog on first run, to
    
    // show the dialog at a more appropriate time move this registration accordingly.
    
    if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_7_1) {
        
        // iOS 7.1 or earlier. Disable the deprecation warnings.
        
#pragma clang diagnostic push
        
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
        
        UIRemoteNotificationType allNotificationTypes =
        
        (UIRemoteNotificationTypeSound |
         
         UIRemoteNotificationTypeAlert |
         
         UIRemoteNotificationTypeBadge);
        
        [application registerForRemoteNotificationTypes:allNotificationTypes];
        
#pragma clang diagnostic pop
        
    } else {
        
        // iOS 8 or later
        
        // [START register_for_notifications]
        
        if (floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_9_x_Max) {
            
            UIUserNotificationType allNotificationTypes =
            
            (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
            
            UIUserNotificationSettings *settings =
            
            [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
            
            [application registerUserNotificationSettings:settings];
            
        } else {
            
            // iOS 10 or later
            
#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0
            
            // For iOS 10 display notification (sent via APNS)
            
            [UNUserNotificationCenter currentNotificationCenter].delegate = self;
            
            UNAuthorizationOptions authOptions =
            
            UNAuthorizationOptionAlert
            
            | UNAuthorizationOptionSound
            
            | UNAuthorizationOptionBadge;
            
            [[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions:authOptions completionHandler:^(BOOL granted, NSError * _Nullable error) {
                
            }];
            
#endif
            
        }[application registerForRemoteNotifications];
        
        // [END register_for_notifications]
        
    }
    
    // Pasting before this
    
    
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(tokenRefreshNotification:)
     
                                                 name:kFIRInstanceIDTokenRefreshNotification object:nil];
    
    
    
    self.applicationInBackground = @(YES);
    
    
    
    return YES;
    
}



- (void)applicationDidBecomeActive:(UIApplication *)application {
    
    [self connectToFcm];
    
    self.applicationInBackground = @(NO);
    
}



- (void)applicationDidEnterBackground:(UIApplication *)application {
    
    [[FIRMessaging messaging] disconnect];
    
    self.applicationInBackground = @(YES);
    
    NSLog(@"Disconnected from FCM");
    
}



- (void)tokenRefreshNotification:(NSNotification *)notification {
    
    // Note that this callback will be fired everytime a new token is generated, including the first
    
    // time. So if you need to retrieve the token as soon as it is available this is where that
    
    // should be done.
    
    NSString *refreshedToken = [[FIRInstanceID instanceID] token];
    
    NSLog(@"InstanceID token: %@", refreshedToken);
    
    
    
    // Connect to FCM since connection may have failed when attempted before having a token.
    
    [self connectToFcm];
    
    
    
    [FirebasePlugin.firebasePlugin sendToken:refreshedToken];
    
}



- (void)connectToFcm {
    
    [[FIRMessaging messaging] connectWithCompletion:^(NSError * _Nullable error) {
        
        if (error != nil) {
            
            NSLog(@"Unable to connect to FCM. %@", error);
            
        } else {
            
            NSLog(@"Connected to FCM.");
            
            NSString *refreshedToken = [[FIRInstanceID instanceID] token];
            
            NSLog(@"InstanceID token: %@", refreshedToken);
            
        }
        
    }];
    
}



- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
    
    NSDictionary *mutableUserInfo = [userInfo mutableCopy];
    
    
    
    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];
    
    
    
    // Pring full message.
    
    NSLog(@"%@", mutableUserInfo);
    
    
    
    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];
    
}



- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo

fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler {
    
    
    
    NSDictionary *mutableUserInfo = [userInfo mutableCopy];
    
    
    
    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];
    
    
    
    // Pring full message.
    
    NSLog(@"%@", mutableUserInfo);
    
    
    
    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];
    
}



// [START ios_10_data_message]

// Receive data messages on iOS 10+ directly from FCM (bypassing APNs) when the app is in the foreground.

// To enable direct data messages, you can set [Messaging messaging].shouldEstablishDirectChannel to YES.

- (void)messaging:(FIRMessaging *)messaging didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
    
    NSLog(@"Received data message: %@", remoteMessage.appData);
    
}

// [END ios_10_data_message]

#if defined(__IPHONE_10_0) && __IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0

- (void)userNotificationCenter:(UNUserNotificationCenter *)center

       willPresentNotification:(UNNotification *)notification

         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler {
    
    NSDictionary *mutableUserInfo = [notification.request.content.userInfo mutableCopy];
    
    
    
    [mutableUserInfo setValue:self.applicationInBackground forKey:@"tap"];
    
    
    
    // Pring full message.
    
    NSLog(@"%@", mutableUserInfo);
    
    
    
    [FirebasePlugin.firebasePlugin sendNotification:mutableUserInfo];
    
}



// Receive data message on iOS 10 devices.

- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
    
    // Print full message
    
    NSLog(@"%@", [remoteMessage appData]);
    
}

#endif



@end

**Comment by soulemanou** [comment]
please some one help me please

**Comment by manojkumardesai** [comment]
I got it resolved by implementing didReceiveMessage method in delegate file. It started working after that.

Full explanation in the above thread..

https://github.com/arnesson/cordova-plugin-firebase/issues/518#issuecomment-361949119 @soulemanou

**Comment by soulemanou** [comment]
thank you for answering @manojkumardesai  . i already have implemented that method in my Appdelegate.m file but its not bieng called  for some reason

**Comment by soulemanou** [comment]
please let me know if you have any ideas @manojkumardesai .

**Comment by soulemanou** [comment]
@manojkumardesai  . I am using ionic framework  and i have replace My AppDelegate+FirebasePluginFile.m with the one added in the comment above but its still not being called for some reason
