### ISSUE TITLE
com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by csotomon** [arnesson/cordova-plugin-firebase#533]
Hi, i'm having this error building cordova android

:compileDebugSources
:transformClassesWithDexBuilderForDebug

:transformDexArchiveWithExternalLibsDexMergerForDebug
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info
 or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 43s
35 actionable tasks: 35 executed
(node:81946) UnhandledPromiseRejectionWarning: Error: /Users/camilo/hexaco/aoc/mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 43s
    at ChildProcess.whenDone (/Users/camilo/hexaco/aoc/mobile/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:159:13)
    at maybeClose (internal/child_process.js:943:16)
    at Socket.stream.socket.on (internal/child_process.js:363:11)
    at Socket.emit (events.js:159:13)
    at Pipe._handle.close [as _onclose] (net.js:568:12)
(node:81946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:81946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by csotomon** [comment]
The problem was the google-plus plugin.

**Comment by welkensoyo** [comment]
This is resolved with adding 

> cordova.system.library.7=com.android.support:appcompat-v7:27.1.0
To your project.properties

**Comment by jpduckwo** [comment]
I am using cordova-plugin-firebase and cordova-plugin-googleplus and I'm getting this issue all of a sudden when then were previously working together. @welkensoyo's fix did not solve it for me. @csotomon did you do anything to solve it with the google-plus plugin?

**Comment by Unicorn808** [comment]
I have the exact same problem, and @welkensoyo's fix didn't work. Is there any way to have both these plugins work side by side?

**Comment by mikilion** [comment]
I'm getting same issue using cordova-plugin-firebase and cordova-plugin-googleplus.
I solved by editing ..\platforms\android\project.properties file
from:
`cordova.system.library.8=com.google.android.gms:play-services-auth:11.8.0
 cordova.system.library.9=com.google.android.gms:play-services-identity:11.8.0`
to:
`cordova.system.library.8=com.google.android.gms:play-services-auth:+
cordova.system.library.9=com.google.android.gms:play-services-identity:+`

**Comment by AFMiziara** [comment]
After some hours stuck on this same problem I figured out how to fix:

- go to: `{project_path}/plugins/cordova-plugin-firebase/src/android/build.gradle`
- change: `classpath 'com.google.gms:google-services:3.1.0'` to
`classpath 'com.google.gms:google-services:+'`

I am using those dependencies:
`cordova-android (^7.0.0)`
`cordova-plugin-firebase (^1.0.4)`
`cordova-plugin-splashscreen (^5.0.2)`
`cordova-plugin-statusbar(^2.4.2)`

**Comment by mikilion** [comment]
I definitely solved by installing the cordova-android-play-services-gradle-release plugin; avoiding to manually change plugin versions.
