### ISSUE TITLE
 Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']    > For input string: "+", again

### ISSUE THREAD

**Issue by rtm** [arnesson/cordova-plugin-firebase#742]
Even after installing `cordova-android-{firebase,support,play-services}-gradle-release`, I still get

```
Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > For input string: "+"
```

I notice the following two lines referring to different versions of `com.google.gms:google-servcies`:

```
plugins/cordova-plugin-firebase/src/android/build.gradle:6:        classpath 'com.google.gms:google-services:3.1.0'
plugins/cordova-support-google-services/build.gradle:9:        classpath 'com.google.gms:google-services:3.2.0'
```

Could this 3.1.0 vs. 3.2.0 be the problem, and if so how would one deal with that?

I am also using `cordova-plugin-firebase-dynamiclinks`, if that is relevant.
I notice that there is a version 1.2 of the google services plugin, which references v4.0 of `com.google.gms:google-services`; is there any point in trying that?

**Comment by DualH** [comment]
Hi @rtm for fix this problem go to 
/platforms/android/cordova-support-google-services

In this directory find the file {APP}-build.gradle

Open and comment the next line

`apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`

**Comment by vc-hitesh** [comment]
Hello rtm,

I have faced similar issue of this. To resolve this issue open that gradle and replace + to a specific version.
classpath 'com.android.tools.build:gradle:+'
classpath 'com.google.gms:google-services:+'
change that to:
**classpath 'com.android.tools.build:gradle:2.2.1'
classpath 'com.google.gms:google-services:3.1.1'**

**Comment by angemimi** [comment]
Thank you very much @DualH

**Comment by soumak77** [comment]
closing as resolved

**Comment by mesqueeb** [comment]
Hello everyone (and especially @DualH and @vc-hitesh )

I first had the problem with input string `"+"`. Then when trying some solutions from here:
go to `/platforms/android/cordova-support-google-services` and change to
- `classpath 'com.android.tools.build:gradle:2.2.1'` (which was `+`)

And then in the same file comment out this line:
 `apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`

I get a lot of version mismatch errors:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/3253920/51308468-87a1a100-1a85-11e9-9785-3d300fc82901.png">

I'm not sure about how to align all the instances of the required gradle / firebase versions for my plugins.

**Would any of you be so kind and see if you can point me in the right direction?**
I tried so many things but am really lost and confused about these versions now.

I need to use firestore and the latest [android releases for firestore](https://firebase.google.com/support/release-notes/android) say it requires 17.+, so that's what I filled in the versions of `FIREBASE_VERSION` and `PLAY_SERVICES_VERSION`.

This is from my package.json
```json
"plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-inappbrowser": {},
            "cordova-plugin-wkwebview-engine": {},
            "cordova-plugin-x-socialsharing": {
                "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
            },
            "cordova-plugin-googleplus": {
                "REVERSED_CLIENT_ID": "com.googleusercontent.apps.1062218916578-8tpir9805stvm1oojb73ii42qbigb2bv",
                "WEB_APPLICATION_CLIENT_ID": "1062218916578-oc5pu1atcblj7fcpq571uded5v9u3vof.apps.googleusercontent.com",
                "PLAY_SERVICES_VERSION": "17.+"
            },
            "cordova-android-firebase-gradle-release": {
                "FIREBASE_VERSION": "17.+"
            },
            "cordova-plugin-firebase": {},
            "cordova-android-play-services-gradle-release": {
                "PLAY_SERVICES_VERSION": "17.+"
            }
        },
```
and from my config.xml
```xml
 <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
    <plugin name="cordova-plugin-inappbrowser" spec="^3.0.0" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.4" />
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <plugin name="cordova-plugin-x-socialsharing" spec="^5.4.4">
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="24.1.1+" />
    </plugin>
    <plugin name="cordova-plugin-googleplus" spec="7.0.0">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.1062218916578-8tpir9805stvm1oojb73ii42qbigb2bv" />
        <variable name="WEB_APPLICATION_CLIENT_ID" value="1062218916578-oc5pu1atcblj7fcpq571uded5v9u3vof.apps.googleusercontent.com" />
        <variable name="PLAY_SERVICES_VERSION" value="17.+" />
    </plugin>
    <plugin name="cordova-android-firebase-gradle-release" spec="^2.0.0">
        <variable name="FIREBASE_VERSION" value="17.+" />
    </plugin>
    <plugin name="cordova-plugin-firebase" spec="^2.0.5" />
    <plugin name="cordova-android-play-services-gradle-release" spec="^2.0.0">
        <variable name="PLAY_SERVICES_VERSION" value="17.+" />
    </plugin>
    <engine name="ios" spec="^4.5.5" />
    <engine name="android" spec="^7.1.4" />
```

Thank you very much for your help.

**Comment by rtm** [comment]
I've pulled the plug on Cordova and its hot mess of version conflicts between Android, Cordova, Cordova platforms, and Cordova plugins. I wasted far too many hours and days of my life trying to get things to work. I delayed new features because I knew the pain that would be involved. I'm writing PWAs now, and life is sweet. Just say no.

**Comment by mesqueeb** [comment]
@rtm well, cordova works beautifully for all plugins for iOS for me. It's just all these android specific gradle versions I think. How can I know which ones I need to set for which plugins?

PS, I can't say no to android app for my client. But don't want to start learning JAVA just to write android apps lol......

**Comment by mesqueeb** [comment]
if I try to put all versions of firebase and google play to 16.0.6 I get warning like this:
```
> Could not find com.google.firebase:firebase-auth:16.0.6.
> Could not find com.google.firebase:firebase-config:16.0.6.
> Could not find com.google.firebase:firebase-common:16.0.6.
> Could not find com.google.firebase:firebase-analytics-impl:16.0.6.
> Could not find com.google.android.gms:play-services-auth:16.0.6.
> Could not find com.google.android.gms:play-services-identity:16.0.6.
> Could not find com.google.android.gms:play-services-ads-identifier:16.0.6.
> Could not find com.google.firebase:firebase-measurement-connector-impl:16.0.6.
> Could not find com.google.android.gms:play-services-basement:16.0.6.
> Could not find com.google.android.gms:play-services-measurement-api:16.0.6.
> Could not find com.google.firebase:firebase-common:16.0.6.
```

And many more, and for each those lines a bunch of files it "searched" through.

Does anyone know what is the correct firebase & google play version to make this plugin work on Android?

**Comment by mesqueeb** [comment]
If I try to put everything on `16.+` i get these errors:
```
Failed to notify dependency resolution listener.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.0.5,16.0.5], [16.0.0,16.0.0]], but resolves to 16.0.5. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> The library com.google.firebase:firebase-analytics is being requested by various other libraries at [[16.0.6,16.0.6], [16.0.1,16.0.1]], but resolves to 16.0.6. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```

I'm not sure what is trying to access `com.google.android.gms:play-services-measurement-base`, and firebase analytics is from this package I think!

**Comment by mesqueeb** [comment]
fixed it!

@rtm don't give up on cordova! you can do it!

**Comment by bryanjorgeflores** [comment]
Thank you so much @DualH

**Comment by pdelaby** [comment]
Thanks @DualH  for the solution ! 
However, this involves changing a generated file. It will be tricky to implement on a automated build (ex: on Ionic AppFlow or Jenkins). Does someone have a solution suitable for continuous integration ?

**Comment by OyebisiJemil** [comment]
> Hi @rtm for fix this problem go to
> /platforms/android/cordova-support-google-services
> 
> In this directory find the file {APP}-build.gradle
> 
> Open and comment the next line
> 
> `apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`
> 
> Next, re run
> 
> `ionice cordova run android`

Thanks, this works for me!

**Comment by JerryBels** [comment]
@DualH solution is no good. I implemented it a few weeks ago, thought I was good to go... I just went through many hours of debug not knowing why Google Login wasn't working anymore. Then I remembered about this. Removed the plugin that was giving errors, removed my fix, rebuilt everything... It works again. Be very careful when implementing this solution.

**Comment by hounaine** [comment]
Solution of @DualH did not work for me.
I found com.google.gms:google-services:4.2.0 requires a plugin called
 strict-version-matcher-plugin:1.1.0 but cannot find in repositories of app-build.gradle so you need to add the repository where  strict-version-matcher-plugin:1.1.0 is located. 
strict-version-matcher-plugin:1.1.0 is located in mavenLocal() and maven repository should be written that way.
here is how should look you app-build.gradle file:
buildscript {
    repositories {
        maven { url "https://maven.google.com" }
		jcenter()
        mavenCentral()
		mavenLocal()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:+'
        classpath 'com.google.gms:google-services:+'
    }
}

// apply plugin: 'com.google.gms.google-services.GoogleServicesPlugin'
// class must be used instead of id(string) to be able to apply plugin from non-root gradle file
ext.postBuildExtras = {
    apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
}
PLEASE refer to this post https://stackoverflow.com/questions/53076998/could-not-find-com-google-android-gmsstrict-version-matcher-plugin1-1-0 that lacks that the problem comes from the strict-version-matcher-plugin:1.1.0 not found.

**Comment by zto-sbenning** [comment]
Hello, why this is close? What is the fix?
I still encounter this issue:

`
Failed to apply plugin [id 'com.google.gms.google-services']

> Cannot add extension with name 'googleServices', as there is an extension already registered with that name.
`

My `ionic info`:

`
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.2.0
    Cordova Platforms  : android 7.1.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    Node              : v8.11.4
    npm               : 5.6.0
    OS                : macOS High Sierra
    Xcode             : Xcode 10.1 Build version 10B61

Environment Variables:

    ANDROID_HOME : /Users/zento/Library/Android/sdk

Misc:

    backend : pro
`

We have to integrate with Jenkins for CI. And as for other the fix from @DualH is resolving the build, but then the plugin won't works.

What is the resolution for this closed issue please?

**Comment by zhiyilee** [comment]
Hi @DualH I have followed your solution. that's ok. but I have got these error continuously.

```
BUILD FAILED in 7s
/Volumes/Work/Hybrid/15_SmartBeach/projects/CUSTOMER/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[17.0.0,17.0.0], [17.2.2,17.2.2]], but resolves to 17.2.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
```
Do you have any solution please?

```
Ionic:

   Ionic CLI          : 5.4.15 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.1.0
   Cordova Plugins   : cordova-plugin-ionic-webview 4.0.1, (and 23 other plugins)

Utility:

   cordova-res : 0.9.0
   native-run  : not installed

System:

   Android SDK Tools : 26.1.1 (/Users/stormlong/Library/Android/sdk)
   NodeJS            : v10.16.3 (/usr/local/bin/node)
   npm               : 6.13.3
   OS                : macOS Mojave

```

This is my environment.

Thank you in advance.

**Comment by DualH** [comment]
> Hi @DualH I have followed your solution. that's ok. but I have got these error continuously.
> 
> ```
> BUILD FAILED in 7s
> /Volumes/Work/Hybrid/15_SmartBeach/projects/CUSTOMER/platforms/android/gradlew: Command failed with exit code 1 Error output:
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Failed to capture fingerprint of input files for task ':app:preDebugBuild' property 'compileManifests' during up-to-date check.
> > The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[17.0.0,17.0.0], [17.2.2,17.2.2]], but resolves to 17.2.2. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> ```
> 
> Do you have any solution please?
> 
> ```
> Ionic:
> 
>    Ionic CLI          : 5.4.15 (/usr/local/lib/node_modules/ionic)
>    Ionic Framework    : ionic-angular 3.9.2
>    @ionic/app-scripts : 3.2.4
> 
> Cordova:
> 
>    Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
>    Cordova Platforms : android 8.1.0
>    Cordova Plugins   : cordova-plugin-ionic-webview 4.0.1, (and 23 other plugins)
> 
> Utility:
> 
>    cordova-res : 0.9.0
>    native-run  : not installed
> 
> System:
> 
>    Android SDK Tools : 26.1.1 (/Users/stormlong/Library/Android/sdk)
>    NodeJS            : v10.16.3 (/usr/local/bin/node)
>    npm               : 6.13.3
>    OS                : macOS Mojave
> ```
> 
> This is my environment.
> 
> Thank you in advance.

Hello @zhiyilee, I migrated to [FirebaseX](https://github.com/dpa99c/cordova-plugin-firebasex) caused the cordova-plugni-firebase is unmaintained currently

Best regards 👋

**Comment by zhiyilee** [comment]
Thank you @DualH for your kindly reply. FirebaseX will help me. 😘😘😘

**Comment by gustavomts20** [comment]
> Hi @rtm for fix this problem go to /platforms/android/cordova-support-google-services
> 
> In this directory find the file {APP}-build.gradle
> 
> Open and comment the next line
> 
> `apply plugin: com.google.gms.googleservices.GoogleServicesPlugin`
> 
> Next, re run
> 
> `ionice cordova run android`

I am using capacitor for the build, where would I change that? Thanks!
